name: Cloudflare Pages Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      deployments: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Copy root files to export/
        run: |
          mkdir -p export
          rsync -av --exclude='.git' --exclude="node_modules" --exclude="export" --exclude=".github" ./ export/

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: blaise-website
          directory: export
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}